In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

## Create and Read

#### 1D Array

In [6]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [7]:
type(arr1)

numpy.ndarray

In [8]:
arr1.shape

(5,)

In [9]:
arr1.dtype

dtype('int32')

In [10]:
arr1.ndim

1

In [11]:
arr1.size

5

##### 2D Array

In [13]:
arr2 = np.array([[1, 4, 5], [6, 7, 4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape   # (row, column)

(2, 3)

In [16]:
arr2.dtype

dtype('int32')

In [17]:
arr2.size

6

#### 3D Array

In [24]:
arr3 = np.array([[[1, 4, 5], [6, 7, 4]], [[3, 5, 4], [5, 8, 7]], [[6,5, 4], [2, 5, 8]]])

In [25]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[6, 5, 4],
        [2, 5, 8]]])

In [26]:
arr3.ndim

3

In [27]:
arr3.shape

(3, 2, 3)

In [28]:
arr3.size

18

### Create random arrays

In [31]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.64466822, 0.27168542, 0.82732016],
        [0.76846903, 0.29689322, 0.6652847 ]],

       [[0.28981239, 0.77392619, 0.32923958],
        [0.04521488, 0.40700101, 0.09455681]],

       [[0.14701839, 0.32534059, 0.24211988],
        [0.18015562, 0.26701297, 0.22542867]]])

In [32]:
randomArr.dtype

dtype('float64')

In [33]:
zeros = np.zeros((3,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [34]:
zeros.ndim

3

In [36]:
full = np.full((3, 2, 3), 8)
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [37]:
ones = np.ones((3, 2, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [38]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[6, 5, 4],
        [2, 5, 8]]])

In [42]:
arr3[0][0][2]

5

In [46]:
arr3[0:1]

array([[[1, 4, 5],
        [6, 7, 4]]])

In [47]:
arr3[-1]

array([[6, 5, 4],
       [2, 5, 8]])

In [50]:
arr3[1][0][1]

5

In [52]:
arr3[1, 0, 1]

5

#### Update & Delete

In [53]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [54]:
a1

array([[[0.82058114, 0.75708916],
        [0.56021745, 0.95231485],
        [0.24532852, 0.84430712]],

       [[0.32853286, 0.64349478],
        [0.09271596, 0.358669  ],
        [0.20394927, 0.30450338]]])

In [55]:
a2

array([[[0.51034576, 0.29450144],
        [0.44337335, 0.10672624],
        [0.32149785, 0.91902251]],

       [[0.33776397, 0.96517631],
        [0.8873047 , 0.33082794],
        [0.91714459, 0.02991393]]])

In [56]:
np.add(a1, a2)

array([[[1.3309269 , 1.0515906 ],
        [1.00359081, 1.05904109],
        [0.56682637, 1.76332964]],

       [[0.66629684, 1.60867109],
        [0.98002066, 0.68949694],
        [1.12109386, 0.33441731]]])

In [57]:
np.subtract(a1, a2)

array([[[ 0.31023538,  0.46258771],
        [ 0.1168441 ,  0.8455886 ],
        [-0.07616934, -0.07471539]],

       [[-0.00923111, -0.32168153],
        [-0.79458874,  0.02784107],
        [-0.71319532,  0.27458945]]])

In [58]:
np.divide(a1, a2)

array([[[ 1.60789254,  2.57074855],
        [ 1.26353433,  8.92296808],
        [ 0.76307979,  0.91870124]],

       [[ 0.97266993,  0.66671216],
        [ 0.10449168,  1.08415573],
        [ 0.22237418, 10.17931711]]])

In [61]:
np.multiply(a1, a2)

array([[[0.4187801 , 0.22296385],
        [0.24838549, 0.10163698],
        [0.07887259, 0.77593725]],

       [[0.11096657, 0.62108592],
        [0.0822673 , 0.11865773],
        [0.18705097, 0.00910889]]])

### statistical operations

In [64]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2, 8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [65]:
sqrt

5.0

In [66]:
abs

2

In [67]:
power

256

In [68]:
log

3.2188758248682006

In [69]:
mins

0.09271595684526834

In [70]:
maxs

0.9651763072021443

### Update the values

In [71]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[6, 5, 4],
        [2, 5, 8]]])

In [72]:
arr3[0, 0, 2] = 500

In [73]:
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  6,   5,   4],
        [  2,   5,   8]]])

In [74]:
arr3.sort()
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  4,   5,   6],
        [  2,   5,   8]]])

In [75]:
arr3.shape

(3, 2, 3)

### Reshape

In [78]:
arr3_reshape = arr3.reshape((2, 3, -1))

In [79]:
arr3_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  4,   5,   6],
        [  2,   5,   8]]])

In [80]:
arr3_reshape.shape

(2, 3, 3)

#### Appending and inserting

In [82]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [83]:
# Create a new array
new_array = np.ones((3, 2, 3))
new_array


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [84]:
appd = np.append(zeros, new_array, axis=0)   ## axis 0 = row, axis 1 = column
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [85]:
# Insert 
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [86]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [87]:
inserted_array = np.insert(zeros, 1, new_array, axis = 0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

#### Delete

In [88]:
arr4 = np.random.rand(3, 2, 3)
arr4

array([[[0.0380152 , 0.39621669, 0.64795295],
        [0.67119485, 0.5056724 , 0.30070688]],

       [[0.26868721, 0.04127936, 0.26462184],
        [0.14079391, 0.49342453, 0.21006431]],

       [[0.48934732, 0.24499633, 0.56056784],
        [0.74389511, 0.1024412 , 0.31828749]]])

In [90]:
# delete the array
arr5 = np.delete(arr4, 0, axis=1)

In [91]:
arr5

array([[[0.67119485, 0.5056724 , 0.30070688]],

       [[0.14079391, 0.49342453, 0.21006431]],

       [[0.74389511, 0.1024412 , 0.31828749]]])

In [92]:
np.save("new_array", arr5)

In [94]:
np.load("new_array.npy")

array([[[0.67119485, 0.5056724 , 0.30070688]],

       [[0.14079391, 0.49342453, 0.21006431]],

       [[0.74389511, 0.1024412 , 0.31828749]]])